### ISSUE TITLE
weiheng.tech link in README failed

### ISSUE THREAD

**Issue by zyLiu6707** [WeihengXia0123/weihengxia0123.github.io#1]
The weblink in README `weiheng.tech` cannot reach the target webpage, instead, will show 404 error.

(copy & paste this link to browser can still reach the webpage)

**Comment by WeihengXia0123** [comment]
Thanks very much for your feedback. 

Yes, it's currently directing to the wrong `https://` link. I will correct it now.

I'm closing this issue as it's solved.

**Comment by zyLiu6707** [comment]
Considering use `[weiheng.tech](https://weiheng.tech)` rather than `[weiheng.tech](weiheng.tech)` in your README to fix the problem.

The browser will complete the URL for you if you only type `weiheng.tech`, i.e., add `https://` at the front. But clicking the URL in README will not do so.
